#!/bin/bash
## https://docs.docker.com/docker-hub/builds/advanced/

## GIT_BRANCH equals both invoking branch or tag.
docker build \
  --build-arg SRC_IMAGE_TAG=${GIT_BRANCH%%-*} \
  -t $IMAGE_NAME .
